name: Deploy to Server

on:
  push:
    branches:
      - main  # Passe den Branch an, auf den du diese Action anwenden möchtest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa

    - name: Start SSH agent
      run: |
        eval $(ssh-agent -s)
        ssh-add /root/.ssh/id_rsa

    - name: Add SSH public key to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Sync files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ./id_rsa
        source: "./"
        target: "/var/www/html/internet-seite/"
        strip_components: 1
        debug: true
